version: "3.8"

x-node-base: &node-base
  image: obolnetwork/charon:${CHARON_VERSION:-v0.17.0}
  restart: unless-stopped
  networks: [cluster]
  depends_on: [relay]
  volumes:
    - ./.charon:/opt/charon/.charon/

x-node-env: &node-env
  CHARON_BEACON_NODE_ENDPOINTS: ${CHARON_BEACON_NODE_ENDPOINTS}
  CHARON_LOG_LEVEL: ${CHARON_LOG_LEVEL:-info}
  CHARON_LOG_FORMAT: ${CHARON_LOG_FORMAT:-console}
  CHARON_VALIDATOR_API_ADDRESS: 0.0.0.0:3600
  CHARON_MONITORING_ADDRESS: 0.0.0.0:3620
  CHARON_JAEGER_ADDRESS: 0.0.0.0:6831

x-node-template: &node-template
  <<: *node-base
  environment:
    <<: *node-env
    CHARON_P2P_RELAYS: ${CHARON_P2P_RELAYS}
    CHARON_P2P_TCP_ADDRESS: 0.0.0.0:${CHARON_TEKU_P2P_TCP_ADDRESS_PORT}
  ports:
    - ${CHARON_TEKU_P2P_TCP_ADDRESS_PORT}:${CHARON_TEKU_P2P_TCP_ADDRESS_PORT}/tcp

x-vc-template: &vc-template
  image: consensys/teku:${TEKU_VERSION:-23.5.0}
  networks: [cluster]
  restart: unless-stopped
  command: /scripts/run_validator.sh
  volumes:
    - ./vc-clients/teku:/opt/data
    - ./vc-clients/teku/run_validator.sh:/scripts/run_validator.sh

services:
  #       _                                  _ _            _
  #   ___| |__   __ _ _ __ ___  _ __     ___| (_) ___ _ __ | |_ ___
  #  / __| '_ \ / _` | '__/ _ \| '_ \   / __| | |/ _ \ '_ \| __/ __|
  # | (__| | | | (_| | | | (_) | | | | | (__| | |  __/ | | | |_\__ \
  #  \___|_| |_|\__,_|_|  \___/|_| |_|  \___|_|_|\___|_| |_|\__|___/
  node-0:
    <<: *node-template
    environment:
      <<: *node-env
      CHARON_PRIVATE_KEY_FILE: /opt/charon/.charon/cluster/node0/charon-enr-private-key
      CHARON_LOCK_FILE: /opt/charon/.charon/cluster/node0/cluster-lock.json
      CHARON_JAEGER_SERVICE: node-0
      CHARON_P2P_EXTERNAL_HOSTNAME: node-0

  relay:
    <<: *node-base
    command: relay
    depends_on: []
    environment:
      <<: *node-env
      CHARON_HTTP_ADDRESS: 0.0.0.0:${CHARON_RELAY_PORT}
      CHARON_DATA_DIR: /opt/charon/relay
      CHARON_P2P_EXTERNAL_HOSTNAME: ${CHARON_P2P_EXTERNAL_HOSTNAME}
      CHARON_P2P_TCP_ADDRESS: 0.0.0.0:${CHARON_RELAY_P2P_TCP_ADDRESS_PORT}
    volumes:
      - ./relay:/opt/charon/relay:rw
    ports:
      - ${CHARON_RELAY_P2P_TCP_ADDRESS_PORT}:${CHARON_RELAY_P2P_TCP_ADDRESS_PORT}/tcp
      - ${CHARON_RELAY_PORT}:${CHARON_RELAY_PORT}/tcp

  #             _ _     _       _
  # __   ____ _| (_) __| | __ _| |_ ___  _ __ ___
  # \ \ / / _` | | |/ _` |/ _` | __/ _ \| '__/ __|
  #  \ V / (_| | | | (_| | (_| | || (_) | |  \__ \
  #   \_/ \__,_|_|_|\__,_|\__,_|\__\___/|_|  |___/
  vc-0:
    <<: *vc-template
    depends_on: [node-0]
    environment:
      NODE_NUMBER: 0
    volumes:
      - .charon/cluster/node0/validator_keys:/opt/charon/validator_keys

  #                        _ _             _
  #  _ __ ___   ___  _ __ (_) |_ ___  _ __(_)_ __   __ _
  # | '_ ` _ \ / _ \| '_ \| | __/ _ \| '__| | '_ \ / _` |
  # | | | | | | (_) | | | | | || (_) | |  | | | | | (_| |
  # |_| |_| |_|\___/|_| |_|_|\__\___/|_|  |_|_| |_|\__, |
  #                                                |___/
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.41.0}
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: [cluster]

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-9.3.2}
    depends_on: [prometheus]
    volumes:
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/datasource.yml
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./monitoring/grafana/dashboards:/etc/dashboards
    networks: [cluster]
    ports:
      - "${MONITORING_PORT_GRAFANA}:3000"

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:-v1.5.0}
    networks: [cluster]

  jaeger:
    image: jaegertracing/all-in-one:${JAEGAR_VERSION:-1.41.0}
    networks: [cluster]

networks:
  cluster:
