global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "node-0"
    static_configs:
      - targets: ["node-0:3620"]
  - job_name: "vc-0"
    static_configs:
      - targets: ["vc-0:8008"]
  - job_name: "node-1"
    static_configs:
      - targets: ["node-1:3620"]
  - job_name: "vc-1"
    static_configs:
      - targets: ["vc-1:8008"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
