global:
  scrape_interval: 5s # Set the scrape interval to every 30 seconds.
  evaluation_interval: 5s # Evaluate rules every 30 seconds.

scrape_configs:
  - job_name: "node-lighthouse"
    static_configs:
      - targets: ["node-lighthouse:3620"]
  - job_name: "node-teku"
    static_configs:
      - targets: ["node-teku:3620"]
  - job_name: "node-nimbus"
    static_configs:
      - targets: ["node-nimbus:3620"]
  - job_name: "vc-lighthouse"
    static_configs:
      - targets: ["vc-lighthouse:5064"]
  - job_name: "vc-teku"
    static_configs:
      - targets: ["vc-teku:8008"]
  - job_name: "vc-nimbus"
    static_configs:
      - targets: ["vc-nimbus:8108"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
